config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#index'

  get 'static_pages/index'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'


  #StaticPages
  
  get  '/help',    to: 'static_pages#help', as: 'help'
  get  '/about',   to: 'static_pages#about', as: 'about'
  get  '/contact', to: 'static_pages#contact', as: 'contact'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(string = "")
      basic_title = "RedTemplate"
      if string.blank?
        basic_title
      else
        "#{string} | RedTemplate"
      end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    RedTemplate by GraceSojor.
  </small>
  <nav>
    <ul>
     <li class="nav-item">
        <%= link_to "About", about_path %>
      </li>
       <li class="nav-item">
        <%= link_to "Contact", contact_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div id="app" class="container-fullwidth">
    <nav class="navbar navbar-expand-lg navbar-light bg-faded">
        <a class="navbar-brand" href="#">Project Name</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNavDropdown" class="navbar-collapse collapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to "Home", root_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Help", help_path %>
              </li>
            </ul>
            <ul class="navbar-nav">
              
              <!--% if logged_in? %-->
                <li><%= link_to "Users", '#' %></li> 
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", '#' %></li>
                    <li><%= link_to "Settings", '#' %></li>
                    <li><%= link_to "Log out", '#', method: :delete %></li>
                  </ul>
                </li>

              <!--% else %-->    

                <li><%= link_to "Log in", '#' %></li>
              
              <!--% end %-->
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= full_title(yield(:title)) %>
  </title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <div>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
  <%= render "layouts/footer" %>
  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title,"About")%>

<ul class="nav nav-tabs">
  
  <li class="nav-item">
      <a class="nav-link active" href="#">HTML</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" href="#">CSS</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" href="#">JavaScript</a>
  </li>
  
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
    Preview
    </a>
    
    <div class="dropdown-menu" aria-labelledby="Preview">
      <a class="dropdown-item" href="#">Mobile Phone</a>
      <a class="dropdown-item" href="#">Tablet</a>
      <a class="dropdown-item" href="#">Laptop</a>
      <a class="dropdown-item" href="#">Desktop</a>
    </div>
  </li>
</ul>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help")%>

<h1>Help</h1>
<p>Get help on the LearnWords at the _______________. 
For questions, send email at (student email).
</p>

app/views/static_pages/index.html.erb
<% provide(:title,"Home")%>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | LearnWords</title>
  </head>
  <body>
    
    <!--% if logged_in? %-->

      <div class= "row">
        <aside class="col-md-4">

          <section class="user_info">
            <!--%= render 'shared/user_info' %-->
          </section>
          
          <!-- <section class="stats"> -->
            <!--%= render 'shared/stats' %-->
          <!-- </section> -->
          
         
        </aside>
        
        <!-- <div class="col-md-8"> -->
          <!-- <h3>Micropost Feed</h3> -->
          <!--%= render 'shared/feed' %-->
       <!--  </div> -->
        
      </div>
    
    <!--% else %-->
    
      <div class="center jumbotron">
        <h1>Welcome to LearnWords!</h1>
        <h2>
          This is the home page.
        </h2>
        <!--%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %-->
      </div>
    
    <!--% end %-->

  </body>
</html>